title: Baojun Che's Homepage
page-top-title: Baojun Che
top-section-bg-text: To be or not to be.
home-subtitle: Baojun Che
copyright-text: '&copy; Baojun Che 2023-2025. All Rights Reserved.'
email : bjche25@stu.pku.edu.cn
